//  importing mongoose library for creating a model for validations
import mongoose from 'mongoose';

//  creating the model
const Book__Schema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
    },
    Author: {
      type: String,
      required: true,
    },
    Publish__Year: {
      type: Number,
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

//  exporting the model for future use
export const Book = mongoose.model('Book', { Book__Schema });

//    Id will be auto generated by MongoDb
